version: '3'

services:

  gatus:
    image: docker.io/twinproduction/gatus:v5.7.0
    restart: unless-stopped
    container_name: gatus
    user: '999:999'
    volumes:
      - ./config.yaml:/config/config.yaml:ro
    networks:
      - gatus-network
    ports:
      - "8080:8080"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

networks:
  gatus-network: